# MySQL
storage:
  username: bilibilireward
  password: passwd
  host: localhost
  port: 3306
  database: "bilibilireward"
  table: "bilibilireward"
  useSSL: false
# 储存方式
database: "yaml"
# 绑定该用户的所有视频
bind_user: true
# UID (仅绑定用户和关注奖励可用)
uid: 012345
# 视频AID
bind:
  - 0123456
# 检查状态时间 (单位: 分钟)
check: 10
# 命令头部
header: "&f[&b宣传系统&f]"
# 是否按投币数量执行命令
with_amount: true
# 点赞奖励
like:
  - "tellraw %player% [\"您给视频 %title% 点了一个赞\"]"
  - "give %player% diamond 1"
# 投币奖励
coin:
  - "tellraw %player% [\"您给视频 %title% 投了%coin%个币\"]"
  - "give %player% diamond 1"
# 收藏奖励
folder:
  - "tellraw %player% [\"您收藏了视频 %title%\"]"
  - "give %player% diamond 1"
# 关注奖励
following:
  - "tellraw %player% [\"您关注了UP主\"]"
  - "give %player% diamond 1"
